#!/usr/bin/env python3
"""
Create NPZ dataset file for human scGrapHiC inference - Version 3.
Adapted to work with the output of create_pseudobulk_v2.py

Data pairings (Hi-C <-> RNA) are inferred from filenames.
"""

import numpy as np
import sys
import os
import argparse
from pathlib import Path
from scipy import sparse
from scipy.sparse.csgraph import laplacian
import hicstraw
import json

# =============================================================================
# CONFIGURATION
# =============================================================================

# Base paths
HUMAN_SCGRAPHIC_DIR = Path("/users/ssridh26/scratch/human_scGrapHiC")
T2_OUTPUT_DIR = Path("/users/ssridh26/scratch/t2_human_scgraphic")

# Input directories (Generated by create_pseudobulk_v2.py)
PSEUDOBULK_GEN_DIR = HUMAN_SCGRAPHIC_DIR / "GSE238001/pseudobulk_generated"
SCHIC_BASE_DIR = PSEUDOBULK_GEN_DIR / "scHi-C"
RNA_BASE_DIR = PSEUDOBULK_GEN_DIR / "scRNA-seq"

# Annotations (Static)
CTCF_DIR = HUMAN_SCGRAPHIC_DIR / "annotations/preprocessed/ctcf"
CPG_DIR = HUMAN_SCGRAPHIC_DIR / "annotations/preprocessed/cpg"
BULK_HIC_FILE = Path("/users/ssridh26/4DNFI5IAH9H1.hic")
DATASET_LABELS_PATH = Path("/users/ssridh26/projects/t2_human_scgraphic/dataset_labels.json")

# Parameters matching the checkpoint
PARAMETERS = {
    'resolution': 50000,
    'library_size': 25000,
    'normalization_algorithm': 'library_size_normalization',
    'norm': 'log_norm',
    'remove_borders': 0, 
    'positional_encoding_size': 128
}

CHROM_SIZES = {
    'chr1': 248956422, 'chr2': 242193529, 'chr3': 198295559, 'chr4': 190214555,
    'chr5': 181538259, 'chr6': 170805979, 'chr7': 159345973, 'chr8': 145138636,
    'chr9': 138394717, 'chr10': 133797422, 'chr11': 135086622, 'chr12': 133275309,
    'chr13': 114364328, 'chr14': 107043718, 'chr15': 101991189, 'chr16': 90338345,
    'chr17': 83257441, 'chr18': 80373285, 'chr19': 58617616, 'chr20': 64444167,
    'chr21': 46709983, 'chr22': 50818468
}

def load_labels():
    if os.path.exists(DATASET_LABELS_PATH):
        with open(DATASET_LABELS_PATH) as f:
            return json.load(f)
    return None

LABELS = load_labels()

def get_matching_rna_dir(hic_sample_id):
    """
    Find matching RNA sample directory.
    """
    if not os.path.exists(RNA_BASE_DIR):
        print(f"RNA base dir not found: {RNA_BASE_DIR}")
        return None
        
    rna_dirs = os.listdir(RNA_BASE_DIR)
    
    # Try to extract a core ID and match
    hic_clean = hic_sample_id.replace("GSM", "").split("_")[-1].replace("-HiC", "").replace(".pairs.gz", "")
    
    # Special handling or heuristics
    if "HiC" in hic_clean:
         rna_clean = hic_clean.replace("HiC", "RNA")
    else:
         rna_clean = hic_clean
         
    # Look for fuzzy match
    for r in rna_dirs:
        if rna_clean in r:
            return r
            
    print(f"Could not find RNA match for {hic_sample_id}")
    return None

def normalize(matrix, algorithm, total_count=1):
    if algorithm == 'library_size_normalization':
        return matrix / np.sum(matrix) * total_count
    return matrix

def positional_encoding(sequence_length, d_model):
    pe = np.zeros((sequence_length, d_model))
    position = np.arange(0, sequence_length).reshape(-1, 1)
    div_term = np.exp(np.arange(0, d_model, 2) * -(np.log(10000.0) / d_model))
    pe[:, 0::2] = np.sin(position * div_term)
    pe[:, 1::2] = np.cos(position * div_term)
    return pe

def extract_node_features(chrom, resolution, rna_file):
    """Extract RNA, CTCF, CpG features"""
    chrom_size = CHROM_SIZES[chrom]
    n_bins = chrom_size // resolution + 1
    
    features = np.zeros((n_bins, 5)) 
    
    # RNA
    if rna_file and os.path.exists(rna_file):
        try:
            rna_track = np.load(rna_file)
            if len(rna_track) > n_bins:
                rna_track = rna_track[:n_bins]
            elif len(rna_track) < n_bins:
                 rna_track = np.pad(rna_track, (0, n_bins - len(rna_track)))
            
            rna_track = normalize(rna_track.reshape(-1, 1), PARAMETERS['normalization_algorithm'], PARAMETERS['library_size']).flatten()
            
            if PARAMETERS['norm'] == 'log_norm':
                rna_track = np.log1p(rna_track)
                
            features[:, 0] = rna_track
            features[:, 1] = rna_track 
        except Exception as e:
            print(f"Error loading RNA {rna_file}: {e}")
            
    # CTCF & CpG (Static paths)
    ctcf_path = CTCF_DIR / f"{chrom}_{resolution}.npy"
    cpg_path = CPG_DIR / f"{chrom}_{resolution}.npy"
    
    if ctcf_path.exists():
        ctcf = np.load(ctcf_path).flatten()
        if len(ctcf) >= n_bins: features[:, 2] = ctcf[:n_bins]
        features[:, 3] = features[:, 2] 
        
    if cpg_path.exists():
        cpg = np.load(cpg_path).flatten()
        if len(cpg) >= n_bins: features[:, 4] = cpg[:n_bins]
        
    return features

def get_bulk_hic(chrom, resolution, hic_file):
    try:
        chrom_name = chrom if 'chr' in chrom else f'chr{chrom}'
        hic = hicstraw.HiCFile(str(hic_file))
        chrom_size = CHROM_SIZES[chrom]
        n_bins = chrom_size // resolution + 1
        
        matrix_zoom = hic.getMatrixZoomData(chrom_name, chrom_name, "observed", "NONE", "BP", resolution)
        records = matrix_zoom.getRecords(0, chrom_size, 0, chrom_size)
        
        matrix = np.zeros((n_bins, n_bins), dtype=np.float32)
        for record in records:
            b1, b2 = record.binX // resolution, record.binY // resolution
            if b1 < n_bins and b2 < n_bins:
                matrix[b1, b2] = record.counts
                matrix[b2, b1] = record.counts
        return matrix
    except Exception as e:
        return None

def process_sample(hic_sample_id, rna_sample_id, output_path):
    print(f"Processing Pair: {hic_sample_id} <-> {rna_sample_id}")
    
    chromosomes = [f'chr{i}' for i in range(1, 23)]
    all_node_features = []
    all_targets = []
    all_pes = []
    all_bulk = []
    all_meta = []
    all_indexes = []
    
    for chrom in chromosomes:
        hic_path = SCHIC_BASE_DIR / hic_sample_id / f"{chrom}.npy"
        rna_path = RNA_BASE_DIR / rna_sample_id / f"{chrom}_{PARAMETERS['resolution']}.npy"
        
        if not hic_path.exists():
            continue
            
        target_matrix = np.load(hic_path)
        n_bins = target_matrix.shape[0]
        
        if n_bins < 20: continue 
        
        features = extract_node_features(chrom, PARAMETERS['resolution'], rna_path)
        
        bulk = get_bulk_hic(chrom, PARAMETERS['resolution'], BULK_HIC_FILE)
        if bulk is None:
            bulk = np.zeros_like(target_matrix)
        elif bulk.shape != target_matrix.shape:
            new_bulk = np.zeros_like(target_matrix)
            s = min(bulk.shape[0], target_matrix.shape[0])
            new_bulk[:s, :s] = bulk[:s, :s]
            bulk = new_bulk
            
        pe = positional_encoding(n_bins, PARAMETERS['positional_encoding_size'])
        
        all_node_features.append(features)
        all_targets.append(target_matrix[None, :, :])
        all_pes.append(pe)
        all_bulk.append(bulk[None, :, :])
        
        # Metadata [stage, tissue, cell_type, cell_count]
        stage_id, tissue_id, ct_id, cell_count = 8, 2, 28, 1 # Default Human Blood HSC
        
        if LABELS:
            stage_id = LABELS['stage'].get('human_blood', 8)
            tissue_id = LABELS['tissue'].get('blood', 2)
            
            # Infer cell type from sample ID
            # Iterate through all known cell types to see if they appear in the ID
            found = False
            for cname, cid in LABELS['cell_type'].items():
                if cname in hic_sample_id:
                    ct_id = cid
                    found = True
                    break
            
            if not found:
                # Default to HSC or Unknown if not found
                ct_id = LABELS['cell_type'].get('HSC', 28)

        all_meta.append(np.array([stage_id, tissue_id, ct_id, cell_count]))
        
        # Indexes [chrom_num, 0, start_bin, end_bin]
        # src/visualizations.py uses idx[0], idx[2], idx[3] 
        chr_num = int(chrom.replace("chr", ""))
        all_indexes.append(np.array([chr_num, 0, 0, n_bins]))
        
    if not all_targets:
        print("  No valid chromosomes found.")
        return
        
    def to_object_array(list_of_arrays):
        arr = np.empty(len(list_of_arrays), dtype=object)
        for i, a in enumerate(list_of_arrays):
            arr[i] = a
        return arr

    print(f"  Saving {len(all_targets)} chromosomes with metadata...")
    
    np.savez(
        output_path,
        node_features=to_object_array(all_node_features),
        targets=to_object_array(all_targets),
        pes=to_object_array(all_pes),
        bulk_hics=to_object_array(all_bulk),
        metadatas=to_object_array(all_meta),
        indexes=to_object_array(all_indexes)
    )

def main():
    if not os.path.exists(SCHIC_BASE_DIR):
        print("Waiting for preprocessing to create scHi-C directory...")
        return

    samples = [d for d in os.listdir(SCHIC_BASE_DIR) if os.path.isdir(os.path.join(SCHIC_BASE_DIR, d))]
    print(f"Found {len(samples)} Hi-C samples")
    
    output_dir = T2_OUTPUT_DIR / "processed/generated_npz"
    os.makedirs(output_dir, exist_ok=True)
    
    for sample in samples:
        rna_sample = get_matching_rna_dir(sample)
        if rna_sample:
            out_file = output_dir / f"{sample}.npz"
            # if out_file.exists():
            #     print(f"Skipping {sample}, already exists.")
            #     continue
            process_sample(sample, rna_sample, out_file)
        else:
            print(f"Skipping {sample} (No matching RNA found)")

if __name__ == '__main__':
    main()
